"""empty message

Revision ID: f31f7b385355
Revises: 
Create Date: 2018-10-22 21:41:35.562921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31f7b385355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antropometrias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('braco', sa.Float(), nullable=True),
    sa.Column('torax', sa.Float(), nullable=True),
    sa.Column('cintura', sa.Float(), nullable=True),
    sa.Column('abdomen', sa.Float(), nullable=True),
    sa.Column('quadril', sa.Float(), nullable=True),
    sa.Column('coxa', sa.Float(), nullable=True),
    sa.Column('biceps', sa.Float(), nullable=True),
    sa.Column('triceps', sa.Float(), nullable=True),
    sa.Column('peito', sa.Float(), nullable=True),
    sa.Column('subsCap', sa.Float(), nullable=True),
    sa.Column('axilar', sa.Float(), nullable=True),
    sa.Column('gorduraPerc', sa.Float(), nullable=True),
    sa.Column('aguaPerc', sa.Float(), nullable=True),
    sa.Column('pesoMagro', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.Column('horaInicio', sa.String(length=5), nullable=True),
    sa.Column('horaFim', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'horaInicio', 'horaFim', name='periodo unico')
    )
    op.create_table('tipoAtendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('qtdRetorno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipoEstados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipoRefeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ocupados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('horaI', sa.String(length=5), nullable=False),
    sa.Column('horaF', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataNascimento', sa.DateTime(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=50), nullable=True),
    sa.Column('objetivo', sa.String(length=50), nullable=True),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anamneses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('qtdAtividadeFisica', sa.Integer(), nullable=True),
    sa.Column('tipoExercicio', sa.String(length=150), nullable=True),
    sa.Column('horaAcorda', sa.TIME(), nullable=True),
    sa.Column('padraoRefeicao', sa.String(length=150), nullable=True),
    sa.Column('deficienciaAlimentacaoDiaria', sa.String(length=250), nullable=True),
    sa.Column('necessitaSuplementoAlimentar', sa.String(length=150), nullable=True),
    sa.Column('retencaoLiquido', sa.Boolean(), nullable=True),
    sa.Column('alergiaRemedio', sa.String(length=150), nullable=True),
    sa.Column('alergiaSuplemento', sa.String(length=150), nullable=True),
    sa.Column('intoleranciaAlimentar', sa.String(length=150), nullable=True),
    sa.Column('problemaSaude', sa.String(length=150), nullable=True),
    sa.Column('problemaSaudeFamilia', sa.String(length=150), nullable=True),
    sa.Column('medicacao', sa.String(length=150), nullable=True),
    sa.Column('suplementacao', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipoAtendimento_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('tipoEstado_id', sa.Integer(), nullable=False),
    sa.Column('antropometria_id', sa.Integer(), nullable=True),
    sa.Column('dieta', sa.LargeBinary(), nullable=True),
    sa.Column('pagamento', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['antropometria_id'], ['antropometrias.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['ocupados.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tipoAtendimento_id'], ['tipoAtendimentos.id'], ),
    sa.ForeignKeyConstraint(['tipoEstado_id'], ['tipoEstados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anamnese_id', sa.Integer(), nullable=False),
    sa.Column('tipoRefeicao_id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.TIME(), nullable=False),
    sa.Column('refeicao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['anamnese_id'], ['anamneses.id'], ),
    sa.ForeignKeyConstraint(['tipoRefeicao_id'], ['tipoRefeicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refeicoes')
    op.drop_table('consultas')
    op.drop_table('anamneses')
    op.drop_table('pacientes')
    op.drop_table('ocupados')
    op.drop_table('users')
    op.drop_table('tipoRefeicoes')
    op.drop_table('tipoEstados')
    op.drop_table('tipoAtendimentos')
    op.drop_table('horarios')
    op.drop_table('antropometrias')
    # ### end Alembic commands ###
